name: Scrape Replies

on:
  schedule:
    - cron: "0 * * * *" # 毎時
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl xvfb libxi6 libxrender1 jq
          pip install selenium beautifulsoup4

      - name: Download Chrome & ChromeDriver
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.112/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome

          wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.112/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run scraper
        run: |
          Xvfb :99 & export DISPLAY=:99
          python reply_tracker.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: replies_csv
          path: replies.csv
