name: Scrape Replies

on:
  schedule:
    - cron: '0 * * * *'  # 毎時実行（UTC時間）
  workflow_dispatch:     # 手動でも実行できるようにする

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 安定版を指定

      - name: Install dependencies
        run: |
          pip install selenium beautifulsoup4
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.112/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run script
        run: python reply_tracker.py

      - name: Upload result CSV
        uses: actions/upload-artifact@v4
        with:
          name: replies_csv
          path: replied_user_ids_*.csv
