name: Scrape Replies

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に自動実行
  workflow_dispatch:      # 手動実行も有効にする

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl jq xvfb libxi6 libgconf-2-4

      - name: Install Chrome & ChromeDriver (latest stable)
        run: |
          wget https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json -O versions.json
          URL=$(jq -r '.channels.Stable.downloads.chrome[] | select(.platform == "linux64") | .url' versions.json)
          DRIVER_URL=$(jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url' versions.json)

          wget $URL -O chrome.zip
          unzip chrome.zip -d chrome
          wget $DRIVER_URL -O chromedriver.zip
          unzip chromedriver.zip -d chromedriver

          sudo mv chrome/linux64/chrome /usr/local/bin/google-chrome
          sudo mv chromedriver/linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/google-chrome /usr/local/bin/chromedriver

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: pip install selenium beautifulsoup4

      - name: Run reply tracker
        run: |
          Xvfb :99 &
          export DISPLAY=:99
          python reply_tracker.py

      - name: Upload result CSV
        uses: actions/upload-artifact@v4
        with:
          name: replies_csv
          path: replies_*.csv
