name: Track Replies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 毎時実行（任意）

jobs:
  reply-tracking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb jq

      - name: Download Chrome & Chromedriver (latest stable)
        run: |
          wget https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json -O versions.json
          URL=$(jq -r '.channels.Stable.downloads.chrome[] | select(.platform == "linux64") | .url' versions.json)
          DRIVER_URL=$(jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url' versions.json)

          wget $URL -O chrome.zip
          unzip chrome.zip
          wget $DRIVER_URL -O chromedriver.zip
          unzip chromedriver.zip

          sudo mv chrome-linux64/chrome /usr/local/bin/google-chrome
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/google-chrome /usr/local/bin/chromedriver

      - name: Install Python packages
        run: |
          pip install -r requirements.txt

      - name: Run Reply Tracker
        run: |
          Xvfb :99 &
          export DISPLAY=:99
          python reply_tracker.py

      - name: Upload CSV Result
        uses: actions/upload-artifact@v3
        with:
          name: reply-results
          path: '*.csv'
